#@TODO normalize path so escape characterdatabase_location
database_location = 'sqlite:///C:\\rykomanager\\rykomanager.db'
annex_docx = 'C:\\rykomanager\\mergefield_docs\\aneks_wzor.docx'
record_docx = 'C:\\rykomanager\\mergefield_docs\\wz.docx'
summary_docx = 'C:\\rykomanager\\mergefield_docs\\Zalacznik_IV_-_Wniosek_o_pomoc_2018-2019.doc'
applicaton_docx_5 = 'C:\\rykomanager\\mergefield_docs\\Zalacznik_V_-_Oswiadczenie_szkoly_2018-2019.docx'
application_docx_5a = 'C:\\rykomanager\\mergefield_docs\\Zalacznik_VA_-_Ewidencja_dostaw_2018-2019.docx'
contract_docx = 'C:\\rykomanager\\mergefield_docs\\Zalacznik_VIII_Umowa_2018-2019.docx'
register_docx = 'C:\\rykomanager\\mergefield_docs\\rejestr.docx'
#output_dir_main = 'C:\\rykomanager\\program_2018_2019_sem1'
output_dir_main = 'C:\\rykomanager\\program_2018_2019_sem2'
output_dir_school = 'szkoly'
annex_folder_name = 'AneksyIumowy'
contract_dir_name = 'Umowy'
annex_dir_name = 'Aneksy'
record_folder_name = 'WZ'
#libreoffice_converter = 'C:\\Program Files\\LibreOffice\\program\\soffice.exe' # development server
libreoffice_converter = 'C:\\Program Files (x86)\\LibreOffice\\program\\soffice.exe' #production server
#current_program_id = 1
current_program_id = 2
devDebug = True